name: Firebase Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "Packages/vite-react-app/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Updated to the minimum required version for Firebase CLI v13.1.0
          cache: "npm"
          cache-dependency-path: Packages/vite-react-app/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./Packages/vite-react-app

      - name: Build
        run: npm run build
        working-directory: ./Packages/vite-react-app

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        working-directory: ./Packages/vite-react-app

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./Packages/vite-react-app
