name: Deploy Vite React App

on:
  pull_request:
    branches: [main]
    paths:
      - "Packages/vite-react-app/**" # Ensure this is lowercase to match your file structure

jobs:
  test-and-build:
    name: Test & Build on Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: Packages/vite-react-app/package-lock.json # Specify the path to your package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./Packages/vite-react-app # Make sure this matches your directory structure

      - name: Run Tests
        run: npm test
        working-directory: ./Packages/vite-react-app

      - name: Lint Code
        run: npm run lint
        working-directory: ./Packages/vite-react-app

      - name: Build Project
        run: npm run build
        working-directory: ./Packages/vite-react-app
